//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentApp200123.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int Grade { get; set; }
        public int DisciplineId { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual User User { get; set; }
    }
}
